### ISSUE TITLE
Getting 404 Registry returned when trying to run `npm install`

### ISSUE THREAD

**Issue by mtndew1** [bklynate/yelpCamp#1]
Simply cloned and ran npm install and got the error:

 404 Registry returned 404 for GET on https://registry.npmjs.org/yelpCamp
npm ERR! 404 
npm ERR! 404  'yelpCamp' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Han/Desktop/yelpCamp/npm-debug.log

**Comment by bklynate** [comment]
change the name of the application in the package.json from yelpCamp to
yelpcamp

**Comment by mtndew1** [comment]
Thanks.
but it is yelpcamp(lower case) in the package.json.

**Comment by bklynate** [comment]
What command are you typing into the terminal to get your error?

You be running `git clone <yelpcamp url>` , then `cd` into the cloned repo, then run `npm install`
